list: modules/acorn/models/task/columns.yaml
modelClass: Acorn\Models\Task
title: acorn::lang.models.task.label_plural
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
perPageOptions:
  - 20
  - 40
  - 80
  - 100
  - 120
showPageNumbers: true
showSetup: true
showSorting: true
showCheckboxes: false
toolbar:
  buttons: list_toolbar
  search:
    prompt: backend::lang.list.search_prompt
# filter: config_filter.yaml
